steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:${_TAG}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '--region', '${_REGION}', '--platform', 'managed', '--memory', '1Gi', '--allow-unauthenticated']
timeout: 1800s
images:
- 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: flask-template
  _IMAGE_NAME: flask-template
  _TAG: latest